name: CI

on:
  release:
    types: [created]

jobs:
  package:

    name: Soldeer Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: abstract-foundation/foundry-toolchain-zksync@v1

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge build zksync
        run: |
          forge build --zksync
        id: build-zksync
    
      - name: Publish to soldeer.xyz
        env:
          SOLDEER_EMAIL: ${{ secrets.SOLDEER_EMAIL }}
          SOLDEER_PASSWORD: ${{ secrets.SOLDEER_PASSWORD }}
        run: |
          forge soldeer login --email "$SOLDEER_EMAIL" --password "$SOLDEER_PASSWORD"
          VERSION=`echo ${{ github.ref_name }} | sed 's/v//'`
          forge soldeer push --skip-warnings absmate~$VERSION
